# Generated by Django 5.0.4 on 2024-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NomCat', models.CharField(max_length=100, verbose_name='Categoria')),
                ('estado', models.IntegerField(verbose_name='Estado')),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nomMarca', models.CharField(max_length=100, verbose_name='Marca')),
                ('estado', models.IntegerField(verbose_name='Estado')),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('idTipDoc', models.AutoField(primary_key=True, serialize=False)),
                ('nomTipDoc', models.CharField(max_length=100)),
                ('codTipDoc', models.CharField(max_length=20)),
                ('estado', models.IntegerField(verbose_name='Estado')),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nomUser', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apelUser', models.CharField(max_length=100, verbose_name='Apellido')),
                ('numDocUser', models.CharField(max_length=20, verbose_name='NumDocumento')),
                ('CorreoUser', models.CharField(max_length=150, verbose_name='Correo')),
                ('Pass', models.CharField(max_length=40)),
                ('DirUser', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
