# Generated by Django 5.0.4 on 2024-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detallesProd',
            fields=[
                ('idDetalleProd', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('peso', models.CharField(max_length=20)),
                ('dimensiones', models.CharField(max_length=50)),
                ('imgExtra', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'detallesprod',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
