# Generated by Django 5.0.4 on 2024-04-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
